/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora.Controlador;

import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */
public class Pantalla extends javax.swing.JFrame {
    double num1;
    double num2;
    double resultado;
    String operador;
    String historial = "";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        
        

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UnoButton = new javax.swing.JButton();
        DivisionButton = new javax.swing.JButton();
        SieteButton = new javax.swing.JButton();
        PotenciaButtom = new javax.swing.JButton();
        CincoButton = new javax.swing.JButton();
        IgualButton = new javax.swing.JButton();
        SegundoButton = new javax.swing.JButton();
        DividirButtom = new javax.swing.JButton();
        ochoButton = new javax.swing.JButton();
        MenosButton = new javax.swing.JButton();
        seisButton = new javax.swing.JButton();
        SumaButtom = new javax.swing.JButton();
        NueveButton = new javax.swing.JButton();
        MultiplicadorButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TresButton = new javax.swing.JButton();
        HistorialButton = new javax.swing.JButton();
        CeroButton = new javax.swing.JButton();
        BorrarButton = new javax.swing.JButton();
        RaizButtom = new javax.swing.JButton();
        CuatroButton = new javax.swing.JButton();
        PorcentajeButom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        UnoButton.setBackground(new java.awt.Color(0, 0, 0));
        UnoButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        UnoButton.setForeground(new java.awt.Color(255, 255, 255));
        UnoButton.setText("1");
        UnoButton.addActionListener(this::UnoButtonActionPerformed);

        DivisionButton.setBackground(new java.awt.Color(0, 0, 0));
        DivisionButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        DivisionButton.setForeground(new java.awt.Color(255, 255, 255));
        DivisionButton.setText("1/x");
        DivisionButton.addActionListener(this::DivisionButtonActionPerformed);

        SieteButton.setBackground(new java.awt.Color(0, 0, 0));
        SieteButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        SieteButton.setForeground(new java.awt.Color(255, 255, 255));
        SieteButton.setText("7");
        SieteButton.addActionListener(this::SieteButtonActionPerformed);

        PotenciaButtom.setBackground(new java.awt.Color(0, 0, 0));
        PotenciaButtom.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        PotenciaButtom.setForeground(new java.awt.Color(255, 255, 255));
        PotenciaButtom.setText("x²");
        PotenciaButtom.addActionListener(this::PotenciaButtomActionPerformed);

        CincoButton.setBackground(new java.awt.Color(0, 0, 0));
        CincoButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        CincoButton.setForeground(new java.awt.Color(255, 255, 255));
        CincoButton.setText("5");
        CincoButton.addActionListener(this::CincoButtonActionPerformed);

        IgualButton.setBackground(new java.awt.Color(0, 0, 0));
        IgualButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        IgualButton.setForeground(new java.awt.Color(255, 255, 255));
        IgualButton.setText("=");
        IgualButton.addActionListener(this::IgualButtonActionPerformed);

        SegundoButton.setBackground(new java.awt.Color(0, 0, 0));
        SegundoButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        SegundoButton.setForeground(new java.awt.Color(255, 255, 255));
        SegundoButton.setText("2");
        SegundoButton.addActionListener(this::SegundoButtonActionPerformed);

        DividirButtom.setBackground(new java.awt.Color(0, 0, 0));
        DividirButtom.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        DividirButtom.setForeground(new java.awt.Color(255, 255, 255));
        DividirButtom.setText("÷");
        DividirButtom.addActionListener(this::DividirButtomActionPerformed);

        ochoButton.setBackground(new java.awt.Color(0, 0, 0));
        ochoButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        ochoButton.setForeground(new java.awt.Color(255, 255, 255));
        ochoButton.setText("8");
        ochoButton.addActionListener(this::ochoButtonActionPerformed);

        MenosButton.setBackground(new java.awt.Color(0, 0, 0));
        MenosButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        MenosButton.setForeground(new java.awt.Color(255, 255, 255));
        MenosButton.setText("-");
        MenosButton.addActionListener(this::MenosButtonActionPerformed);

        seisButton.setBackground(new java.awt.Color(0, 0, 0));
        seisButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        seisButton.setForeground(new java.awt.Color(255, 255, 255));
        seisButton.setText("6");
        seisButton.addActionListener(this::seisButtonActionPerformed);

        SumaButtom.setBackground(new java.awt.Color(0, 0, 0));
        SumaButtom.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        SumaButtom.setForeground(new java.awt.Color(255, 255, 255));
        SumaButtom.setText("+");
        SumaButtom.addActionListener(this::SumaButtomActionPerformed);

        NueveButton.setBackground(new java.awt.Color(0, 0, 0));
        NueveButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        NueveButton.setForeground(new java.awt.Color(255, 255, 255));
        NueveButton.setText("9");
        NueveButton.addActionListener(this::NueveButtonActionPerformed);

        MultiplicadorButton.setBackground(new java.awt.Color(0, 0, 0));
        MultiplicadorButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        MultiplicadorButton.setForeground(new java.awt.Color(255, 255, 255));
        MultiplicadorButton.setText("x");
        MultiplicadorButton.addActionListener(this::MultiplicadorButtonActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        TresButton.setBackground(new java.awt.Color(0, 0, 0));
        TresButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        TresButton.setForeground(new java.awt.Color(255, 255, 255));
        TresButton.setText("3");
        TresButton.addActionListener(this::TresButtonActionPerformed);

        HistorialButton.setBackground(new java.awt.Color(0, 0, 0));
        HistorialButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        HistorialButton.setForeground(new java.awt.Color(255, 255, 255));
        HistorialButton.setText("--");
        HistorialButton.addActionListener(this::HistorialButtonActionPerformed);

        CeroButton.setBackground(new java.awt.Color(0, 0, 0));
        CeroButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        CeroButton.setForeground(new java.awt.Color(255, 255, 255));
        CeroButton.setText("0");
        CeroButton.addActionListener(this::CeroButtonActionPerformed);

        BorrarButton.setBackground(new java.awt.Color(0, 0, 0));
        BorrarButton.setForeground(new java.awt.Color(255, 255, 255));
        BorrarButton.setText("BORRAR ");
        BorrarButton.addActionListener(this::BorrarButtonActionPerformed);

        RaizButtom.setBackground(new java.awt.Color(0, 0, 0));
        RaizButtom.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        RaizButtom.setForeground(new java.awt.Color(255, 255, 255));
        RaizButtom.setText(" √");
        RaizButtom.addActionListener(this::RaizButtomActionPerformed);

        CuatroButton.setBackground(new java.awt.Color(0, 0, 0));
        CuatroButton.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        CuatroButton.setForeground(new java.awt.Color(255, 255, 255));
        CuatroButton.setText("4");
        CuatroButton.addActionListener(this::CuatroButtonActionPerformed);

        PorcentajeButom.setBackground(new java.awt.Color(0, 0, 0));
        PorcentajeButom.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        PorcentajeButom.setForeground(new java.awt.Color(255, 255, 255));
        PorcentajeButom.setText("%");
        PorcentajeButom.addActionListener(this::PorcentajeButomActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SieteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SegundoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ochoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NueveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SumaButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IgualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DividirButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultiplicadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BorrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(PorcentajeButom, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(RaizButtom)
                                    .addGap(15, 15, 15)
                                    .addComponent(PotenciaButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HistorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HistorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RaizButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PotenciaButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PorcentajeButom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BorrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DividirButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(MultiplicadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(MenosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SumaButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56))
                        .addComponent(IgualButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SieteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CuatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                    .addComponent(UnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ochoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                    .addComponent(SegundoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NueveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addGap(18, 18, 18)
                        .addComponent(CeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("1");
    }//GEN-LAST:event_UnoButtonActionPerformed

    private void DivisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionButtonActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(jTextArea1.getText());
        double division = 1 / num;
        jTextArea1.setText(String.valueOf(division));
    }//GEN-LAST:event_DivisionButtonActionPerformed

    private void SieteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SieteButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("7");
    }//GEN-LAST:event_SieteButtonActionPerformed

    private void PotenciaButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaButtomActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(jTextArea1.getText());
        double potencia = Math.pow(num,2);
        jTextArea1.setText(String.valueOf(potencia));
    }//GEN-LAST:event_PotenciaButtomActionPerformed

    private void CincoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CincoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("5");
    }//GEN-LAST:event_CincoButtonActionPerformed

    private void IgualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualButtonActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(jTextArea1.getText());
        
        double resultado = 0;
    switch(operador){

        case "+":
            resultado = num1 + num2;
            break;

        case "-":
            resultado = num1 - num2;
            break;

        case "*":
            resultado = num1 * num2;
            break;

        case "/":
        
            if(num2 == 0){
                JOptionPane.showMessageDialog(this,"No se puede dividir entre 0");
                return;
            }
            resultado = num1 / num2;
            
        break;
        }
    
    jTextArea1.setText(String.valueOf(resultado));
    }//GEN-LAST:event_IgualButtonActionPerformed

    private void SegundoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("2");
    }//GEN-LAST:event_SegundoButtonActionPerformed

    private void DividirButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DividirButtomActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextArea1.getText());
        operador = "/";
        jTextArea1.setText("");
    }//GEN-LAST:event_DividirButtomActionPerformed

    private void ochoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("8");
    }//GEN-LAST:event_ochoButtonActionPerformed

    private void MenosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextArea1.getText());
        operador = "-";
        jTextArea1.setText("");
    }//GEN-LAST:event_MenosButtonActionPerformed

    private void seisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("6");
    }//GEN-LAST:event_seisButtonActionPerformed

    private void SumaButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaButtomActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextArea1.getText());
        operador = "+";
        jTextArea1.setText("");
    }//GEN-LAST:event_SumaButtomActionPerformed

    private void NueveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NueveButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("9");
    }//GEN-LAST:event_NueveButtonActionPerformed

    private void MultiplicadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicadorButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextArea1.getText());
        operador = "*";
        jTextArea1.setText("");
    }//GEN-LAST:event_MultiplicadorButtonActionPerformed

    private void TresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("3");
    }//GEN-LAST:event_TresButtonActionPerformed

    private void HistorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialButtonActionPerformed
        // TODO add your handling code here:
        historial = historial + num1 + " " + operador + " " + num2 + " = " + resultado + "\n";
        jTextArea1.setText(String.valueOf(resultado));
    }//GEN-LAST:event_HistorialButtonActionPerformed

    private void CeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeroButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("0");
    }//GEN-LAST:event_CeroButtonActionPerformed

    private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
    }//GEN-LAST:event_BorrarButtonActionPerformed

    private void RaizButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaizButtomActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(jTextArea1.getText());
        double raiz = Math.sqrt(num);
        jTextArea1.setText(String.valueOf(raiz));
    }//GEN-LAST:event_RaizButtomActionPerformed

    private void CuatroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuatroButtonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append("4");
    }//GEN-LAST:event_CuatroButtonActionPerformed

    private void PorcentajeButomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeButomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorcentajeButomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarButton;
    private javax.swing.JButton CeroButton;
    private javax.swing.JButton CincoButton;
    private javax.swing.JButton CuatroButton;
    private javax.swing.JButton DividirButtom;
    private javax.swing.JButton DivisionButton;
    private javax.swing.JButton HistorialButton;
    private javax.swing.JButton IgualButton;
    private javax.swing.JButton MenosButton;
    private javax.swing.JButton MultiplicadorButton;
    private javax.swing.JButton NueveButton;
    private javax.swing.JButton PorcentajeButom;
    private javax.swing.JButton PotenciaButtom;
    private javax.swing.JButton RaizButtom;
    private javax.swing.JButton SegundoButton;
    private javax.swing.JButton SieteButton;
    private javax.swing.JButton SumaButtom;
    private javax.swing.JButton TresButton;
    private javax.swing.JButton UnoButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton ochoButton;
    private javax.swing.JButton seisButton;
    // End of variables declaration//GEN-END:variables
}
